//<auto-generated />
global using Gasolutions.Maui.App.Models;
global using Gasolutions.Maui.App.Pages;
global using Gasolutions.Maui.App.Services;
global using Font = Microsoft.Maui.Font;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Text.RegularExpressions;
