//<auto-generated />
global using Barber.Maui.BrandonBarber.Models;
global using Barber.Maui.BrandonBarber.Pages;
global using Barber.Maui.BrandonBarber.Services;
global using Font = Microsoft.Maui.Font;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Text.RegularExpressions;
global using Barber.Maui.BrandonBarber.Utils;
global using CommunityToolkit.Mvvm.Messaging;
global using Barber.Maui.BrandonBarber.Messenger;
global using Microsoft.Maui.Controls.Shapes;
global using Barber.Maui.BrandonBarber.Mobal;
